//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutletApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_TipoProductos
    {
        public int TipoProductoID { get; set; }
        public string Tipo { get; set; }
        public string DescripcionTipoProducto { get; set; }
    }
}
